version: '3.9'

networks:
  default:
    driver: bridge

services:
  whisperx:
    container_name: whisperx
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9200:9200"
    volumes:
      - ./local-dir:/path/in/container
    environment:
      - PYTHONUNBUFFERED=1  # Disable Python's output buffering for real-time logging
    networks:
      - default
    restart: unless-stopped
